name: Echo with env_a environment

on:
  push:
    tags:
      - 'ts_*'
      - 'tb_*'
  workflow_dispatch:

jobs:
  echo-env-var-a:
    runs-on: ubuntu-latest
    environment: env_a
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'ts_')
    
    steps:
      - name: CHeck out repository
        uses: actions/checkout@v2
      
      - name: Echo environment variable
        run: echo "ENV_VAR ${{ vars.ENV_VAR }}"
  echo-env-var-b:
    runs-on: ubuntu-latest
    environment: env_b
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'tb_')
    
    steps:
      - name: CHeck out repository
        uses: actions/checkout@v2
      
      - name: Echo environment variable
        run: echo "ENV_VAR ${{ vars.ENV_VAR }}"
